CREATE TABLE [dbo].[HIGH_TMASTER] (
    [TNO]     INT           IDENTITY (1, 1) NOT NULL,
    [DOT]     DATETIME      NOT NULL,
    [ACID]    INT           NOT NULL,
    [BRID]    CHAR (3)      NOT NULL,
    [TXNTYPE] CHAR (3)      NOT NULL,
    [CHQNO]   INT           NULL,
    [CHQDATE] SMALLDATETIME NULL,
    [TXNAMT]  MONEY         NOT NULL,
    [UID]     INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([TNO] ASC),
    CONSTRAINT [CK_HIGH_TMASTER] CHECK ([TXNTYPE]='CQD' OR [TXNTYPE]='CW' OR [TXNTYPE]='CD'),
    FOREIGN KEY ([ACID]) REFERENCES [dbo].[AMASTER] ([ACID]),
    FOREIGN KEY ([BRID]) REFERENCES [dbo].[BRMASTER] ([BRID]),
    FOREIGN KEY ([UID]) REFERENCES [dbo].[UMASTER] ([UID])
);

