CREATE TABLE [dbo].[PMASTER] (
    [PID]   CHAR (2)     NOT NULL,
    [PNAME] VARCHAR (15) NOT NULL,
    PRIMARY KEY CLUSTERED ([PID] ASC)
);


GO
CREATE TRIGGER CHECK_PRODUCT_ON_DELETION
ON PMASTER
AFTER DELETE
AS BEGIN

-- DECLARE VARIABLES--
-----------------------------
DECLARE @PID		CHAR(2)
DECLARE @CNT		INT

--GET THE VALUES FROM DELETED TABLE --
------------------------------------
SELECT @PID=PID
FROM DELETED

-- FIND THE NO. OF CUSTOMERS FOR THIS PID --
---------------------------------------
SELECT @CNT=COUNT(*) 
FROM AMASTER
WHERE PID=@PID

IF (@CNT!=0) 
BEGIN
PRINT 'YOU CAN NOT DELETE THE PRODUCT'
ROLLBACK TRAN
END
END