CREATE TABLE [dbo].[UMASTER] (
    [UID]   INT          NOT NULL,
    [UNAME] VARCHAR (30) NOT NULL,
    [DESGN] CHAR (1)     NOT NULL,
    PRIMARY KEY CLUSTERED ([UID] ASC),
    CONSTRAINT [CK_UMASTER] CHECK ([DESGN]='C' OR [DESGN]='T' OR [DESGN]='M')
);

