--Step 1: 
--List the transactions corresponding to an account in the descending order

CREATE PROC RUNNING_BAL
(
	@ACID	INT		
)
AS 
BEGIN

DECLARE	@TXNTYPE	CHAR(3),
		@TXNAMT		MONEY,
		@DOT		DATETIME,
		@CBAL		MONEY,
		@RUNBAL		MONEY

SELECT		@CBAL = CBAL
FROM		AMASTER
WHERE		ACID = @ACID

DECLARE CSRRUNBAL CURSOR SCROLL
FOR

SELECT		 TXNTYPE, 
			 TXNAMT,
			 DOT
FROM		TMASTER
WHERE		ACID = @ACID
ORDER BY	DOT DESC

OPEN CSRRUNBAL 
FETCH NEXT FROM CSRRUNBAL
INTO	@TXNTYPE, @TXNAMT, @DOT
WHILE @@FETCH_STATUS = 0

BEGIN
IF ( @TXNTYPE =  'CD')

SET @RUNBAL = @CBAL - @TXNAMT

ELSE 
IF ( @TXNTYPE =  'CW')
SET @RUNBAL = @CBAL + @TXNAMT

PRINT ' ' + @TXNTYPE + CAST(@TXNAMT AS VARCHAR(10)) +  CAST(@DOT AS VARCHAR(10))

FETCH NEXT FROM CSRRUNBAL
INTO	@TXNTYPE, @TXNAMT, @DOT
END

CLOSE CSRRUNBAL
DEALLOCATE CSRRUNBAL
END